export const desafios = [
  "✍️ Escribe una historia en 3 frases.",
  "🎨 Dibuja algo con los ojos cerrados.",
  "💡 Crea una idea de negocio en 1 minuto.",
  "🤖 Diseña un personaje usando solo tres palabras.",
  "🎭 Haz una mini obra de teatro con objetos cercanos.",
  "🎵 Escribe una canción en menos de 5 líneas.",
  "📝 Crea un anuncio publicitario absurdo pero divertido.",
  "🏗️ Piensa en un invento loco y descríbelo.",
  "📸 Toma una foto de algo común pero con una perspectiva inusual.",
  "📚 Escribe el resumen de un libro que no existe.",
  "🎬 Imagina y describe una escena de película épica.",
  "🔮 Si pudieras ver el futuro, ¿qué mensaje te darías a ti mismo?",
  "🌎 Crea una teoría conspirativa completamente ridícula.",
  "🎤 Improvisa un discurso motivacional sobre cualquier objeto cercano.",
  "🏆 Si fueras a ganar un premio, ¿por qué sería?",
  "🚀 Explica cómo funcionaría un viaje en el tiempo sin paradojas.",
  "🧩 Invéntate una nueva palabra y su significado.",
  "🏛️ Si crearas una nueva civilización, ¿cuál sería su regla principal?",
  "👽 Describe la vida en un planeta donde todo es al revés.",
  "🔥 Escribe una frase que motive a alguien a hacer algo increíble hoy.",
];
